### ISSUE TITLE
Jasmine 4.0.1 does not work with jasmine-ts

### ISSUE THREAD

**Issue by air2** [svi3c/jasmine-ts#177]
When I upgrade to Jasmine 4.0.1 I get the following error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/command' is not defined by "exports" in C:\projects\myProject\service\node_modules\jasmine\package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\projects\myProject\service\node_modules\@cspotcode\source-map-support\source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by ert78gb** [comment]
Jasmine 4 has many breaking changes. Have to work on the compatibility

**Comment by ert78gb** [comment]
I think this library is outdated and generates more problems than solves.

Jasmine@4 does not expose `jasmine/lib/command` and I could agree with it. Jasmine@4 also started to support ES6 module but currently it does not support custom module loader. Therefore the `ts-node/esm` loader has to be set to `NODE_OPTIONS` environment variables in order to be able to load the transpiled typescript code. 

The loader is to be set before the node process starts. Otherwise this helper library has to start a new node process. But I think it is an overkill and gives an extra complexity to the jasmine, typescript and ts-node config management and debugging process.

I think it is more clear if we use proper jasmine configuration, so I have created 2 example projects to demonstrate how to setup jasmine@4, typescript with [commonjs](https://github.com/ert78gb/jasmine4-typescript-commonjs-example) and [ES6 module](https://github.com/ert78gb/jasmine4-typescript-es6-module-example) resolution.

**Comment by air2** [comment]
Sorry for my late response, but your 2 examples really helped me to remove the jasmine-ts dependency. Thank u

**Comment by pushkin-** [comment]
@ert78gb Not sure if I'm doing something wrong, but I tried your commonjs example and still get:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath '[./lib/command]()' is not defined by "exports" in [C:\<somepath>\node_modules\jasmine\package.json]()
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:731:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ([C:\<somepath>\node_modules\]()@cspotcode\source-map-support\source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

when running unit tests

**Comment by ert78gb** [comment]
Hi, The example perfectly works for me. If I upgrade every dependency to the latest stable then it still works.

Are you sure did you setup everything correctly?

**Comment by pushkin-** [comment]
@ert78gb yeah I followed everything exactly. This is my jasmine.json:
```
{
	"spec_dir": "./src/**/specs",
	"spec_files": [
		"**/*[sS]pec.ts"
	],
	"helpers": [
		"jasmine-typescript-helper.js"
	]
}
```

Even when I delete `spec_dir` and `spec_files`, I get the error. Maybe the relative helper path is wrong?

**Comment by ert78gb** [comment]
In my example I don't use `source-map-support` Maybe it is miss configured somehow.
I tested with WebStorm/IntelliJ and VSCode Insider and the debugging works without any issue. The debugger stops in the source and spec files too.

In WebStorm I open the package.json and I click on the small play icon before the `test` script.

In VsCode Insider I use the `Debug npm Script` commad.
