### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position xxxx

### ISSUE THREAD

**Issue by Syltty** [svi3c/jasmine-ts#24]
Can't even use the init command...

> jasmine-ts init

SyntaxError: Unexpected token } in JSON at position 5341
    at JSON.parse (<anonymous>)
    at parse (C:\Temp\Projects\otf-server\node_modules\tsconfig\src\tsconfig.ts:195:15)
    at readFileSync (C:\Temp\Projects\otf-server\node_modules\tsconfig\src\tsconfig.ts:181:10)
    at Object.loadSync (C:\Temp\Projects\otf-server\node_modules\tsconfig\src\tsconfig.ts:151:18)
    at readConfig (C:\Temp\Projects\otf-server\node_modules\ts-node\src\index.ts:425:18)
    at Object.register (C:\Temp\Projects\otf-server\node_modules\ts-node\src\index.ts:189:18)
    at Object.<anonymous> (C:\Temp\Projects\otf-server\node_modules\jasmine-ts\src\index.ts:23:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! OTF-server@0.5.1 init: `jasmine-ts init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the OTF-server@0.5.1 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by svi3c** [comment]
Hi, I cannot reproduce your issue.
I just installed jasmine-ts in a fresh npm package and `jasmine-ts init` works on my machine without problems.
I also did a `tsc --init` to have a tsconfig.json file in place.

Did you install ts-node separately? Which version do you have?
```
npm list tsconfig                                                                                                                                                                                                                                                         
foo@1.0.0 ...
└─┬ jasmine-ts@0.2.1
  └─┬ ts-node@3.3.0
    └── tsconfig@6.0.0
```
I don't have src directories within jasmine-ts, ts-node and tsconfig within node_modules.

**Comment by Syltty** [comment]
Sorry, I had an extra comma in the tsconfig and though everything was fine for tsc.
