### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by TimoHocker** [svi3c/jasmine-ts#45]
After setting up my typescript project for jasmine tests I noticed that my ci system fails to run the tests. It always shows this message:

```text
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist' is not defined by "exports" in /drone/src/node_modules/ts-node/package.json
--
 at applyExports (internal/modules/cjs/loader.js:490:9)
 at resolveExports (internal/modules/cjs/loader.js:506:23)
 at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
 at Function.Module._load (internal/modules/cjs/loader.js:841:27)
 at Module.require (internal/modules/cjs/loader.js:1025:19)
 at require (internal/modules/cjs/helpers.js:72:18)
 at Object.<anonymous> (/drone/src/node_modules/jasmine-ts/lib/index.js:6:16)
 at Module._compile (internal/modules/cjs/loader.js:1137:30)
 at Module.replacementCompile (/drone/src/node_modules/append-transform/index.js:60:13) {
 code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
 }
```

after looking at the indicated line in jasmine-ts and the structure of ts-node I changed the import in jasmine-ts' index.js
```js
- const dist_1 = require("ts-node/dist");
+ const dist_1 = require("ts-node");
```

this fixed the issue and from my understanding it doesn't change the behaviour of that import.

**Comment by cblokland90** [comment]
Can this be merged? What workaround can be used until this is merged?

**Comment by TimoHocker** [comment]
like you said, downgrade ts-node. Or make your own jasmine-ts package.
I put an additional command into my ci script that replaces this line of code every time, but it's clearly a bad fix.

This pr can be merged, but it looks like all the authorized people on this repo are inactive.

**Comment by ert78gb** [comment]
The 0.3.2 version contains the fix

**Comment by moustafaalsayeh** [comment]
Still the problem does not works

**Comment by moustafaalsayeh** [comment]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/command' is not defined by "exports" in /usr/local/lib/node_modules/jasmine-ts/node_modules/jasmine/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/local/lib/node_modules/jasmine-ts/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

**Comment by ert78gb** [comment]
please check the [comment](https://github.com/svi3c/jasmine-ts/issues/177#issuecomment-1008292856)

**Comment by moustafaalsayeh** [comment]
> please check the [comment](https://github.com/svi3c/jasmine-ts/issues/177#issuecomment-1008292856)

Thanks it works
